### PR TITLE
Do not verify scripts when saving

### LINKED ISSUE #113: Expert mode don't need to do verifications after each file switch
Currently selecting new file take some time because after each change there is some validation running . This makes editing session really time consuming and not pleasant . But ofc I clearly see reasons why we need this . To keep CAP repo in workable state but give user more comfortable environment : 
- on file modification of any file not directly save changes but create some temp modified copy/patch
- after user did all needed changes he/she suppose to press some kinda of "Submit" button which will do validation and will apply changes in case all valid 
- during one "modification session" user may switch between files faster because we not doing any checks

### PR DESCRIPTION
**Pull request by jesusbv**
Every time a source is saved, it gets verified.
That makes the editing of sources a bit slow
process.

With this changes sources get verified when
leaving source edition or explicitly.

This Fixes #113

### CODE REVIEW

**Comment by jesusbv** [comment]
I have added navigation buttons and a `Check Sources` (instead of `submit`) 

edit_source_not_ok

**Comment by jesusbv** [comment]
edit_source_valid

**Comment by jesusbv** [comment]
sources_not_ok

**Comment by jesusbv** [comment]
sources_ok

**Comment by bear454** [comment]
@jesusbv please rebase on master.

**Pull request merged**
