### PR TITLE
Custom top menu items

### PR DESCRIPTION
**Pull request by bear454**
image

### CODE REVIEW

**Comment by bear454** [comment]
Resolved conflict with rebase on master branch.

**Comment by bear454** [comment]
Rebased on master to resolve merge conflicts.

**Review by jesusbv — APPROVED** [review]
LGTM

**Comment by MalloZup** [comment]
great thing!

**Comment by stefanotorresi** [comment]
I'm not quite clear how does this work.
How can we address a dynamically generated url in the static configuration file?

**Comment by stefanotorresi** [comment]
oh wait, this that `%` _all_ there is to it?
https://github.com/SUSE-Enceladus/blue-horizon/blob/71efdcd82308fce2b6685a23172eb74db0cec345/app/helpers/application_helper.rb#L92

**Comment by bear454** [comment]
https://github.com/SUSE-Enceladus/blue-horizon/blob/master/README.md#top-menu-items ;-)

**Pull request merged**
