### PR TITLE
File uploads

### PR DESCRIPTION
**Pull request by bear454**
Variables with a name ending in _file will be populated with a filename; the file, uploaded by the user via a file input form field, will be stored in sources and written to the terraform workspace during operations.

----

ex variable definition:
```
{"variable":{"key_file": {"type": "string}}}
```

ex terraform usage:
```
output = file(var.key_file)
```
----

Unpopulated:

Screenshot from 2020-10-30 16-25-57

Populated:

Screenshot from 2020-10-30 16-27-16

### CODE REVIEW

**Comment by bear454** [comment]
I'd like to have this supercede #127 because:

* no gem dependencies - #127 adds 6 gems including `mini_magick`. :(
* no database migration
* file is present in terraform workspace instead of separate upload location

**Review by arbulu89 — APPROVED** [review]
@bear454 Great job! It works great.
Just 2 comments:
- I don't really like the button overlaps the underline. This is just a cosmetic things
- It looks like the `Please select a file` popup moves from the place if the file is missing:
label_moving

**Comment by bear454** [comment]
The tooltip issue is a known problem in bootstrap 4. The style issue we can try to hack around, but any fix should also go upstream to EOS.

**Comment by arbulu89** [comment]
> The tooltip issue is a known problem in bootstrap 4. The style issue we can try to hack around, but any fix should also go upstream to EOS.

Ok, that's fine. I just realized the tooltip movement and reported here hehe

**Comment by bear454** [comment]
Screenshot from 2020-11-02 09-09-56

**Comment by arbulu89** [comment]
Hey @bear454 

I see that even with that last commit the button is not placed as shown in the image. Just a heads up.
image

**Pull request merged**
