### PR TITLE
Create file type variables to upload files

### PR DESCRIPTION
**Pull request by arbulu89**
In order to use our terraform code (and I guess it's a quite normal thing), we need to use some files. In this case, we will need to upload the files to the server. I have chosen carrierwave for that. The implementation looks quite straightforward.

The usage is simple. Basically, you add the `file_key` content in the description (this string is configurable in the en.yml file), and this will convert the input in a file input type. As soon as the file is uploaded, it will fill the other text input that we have besides. This is needed to recover the file name we have uploaded if just change the page, as the file input doesn't save anything.

By now, the files are uploaded to `public/uploads` (hardcoded right now, we could make this configurable too).

The unique thing that I don't really like (but I have not found a better way right now) is that I have added the attachment attribute to the `KeyValue` model. This changes a bit how this model is used. Feel free to suggest other options.

This is how it looks like:
image

@bear454 @jesusbv Could you have a look? 

PD: Like the last PR, I will create the UT as soon as the solution is validated by you

### CODE REVIEW

**Comment by bear454** [comment]
As we're currently addressing issues found in QA, for an impending release, I'm putting this on hold.

We'll review after we complete the QA cycle.

**Comment by bear454** [comment]
Please rebase to resolve the test suite issue.

**Comment by arbulu89** [comment]
> Please rebase to resolve the test suite issue.

In any case, the PR doesn't still have the needed UT for the new changes. I just wanted to validate the idea to work on them in the future.

**Comment by arbulu89** [comment]
@bear454 Any update on this? I would like to work 1st in this changes before creating any other change or even creating UT

**Comment by arbulu89** [comment]
Closing. Implemented in https://github.com/SUSE-Enceladus/blue-horizon/pull/164

**Pull request closed without merging**
