### PR TITLE
Rebranding to EOS 4.1

### PR DESCRIPTION
**Pull request by bear454**
image

image

### CODE REVIEW

**Comment by MalloZup** [comment]
looks great :heart:

**Comment by bear454** [comment]
@arbulu89 can you give this a once-over?

**Review by arbulu89 — COMMENTED** [review]
Hi @bear454 .
It looks really nice in general! Great job.
I have found some items that we could change/fix to make it a bit better in my opinion

1. In my opinion the width used by the central frame is to small. I would leverage more screen size. Otherwise, in wide monitors half of the screen is empty:
image

2. The password type variable needs some adjustments. Maybe we need to make the underline shorter:
image

3. The `Download plan` button text is not visible:
image

4. When `plan` button is clicked, we don't have anymore this animated gif with the `in progress` image

**Comment by bear454** [comment]
From d47293b:
image

**Comment by bear454** [comment]
Updated buttons from be81622:
image

**Comment by bear454** [comment]
WRT the width, you need to address that with the EOS maintainers; I'm only implementing the guidance:

https://suse.eosdesignsystem.com/images/layout/desktop-menu.gif

https://suse.eosdesignsystem.com/layout

I _will_ be doing something about the dumb jumbotron though, so that may help.

**Comment by bear454** [comment]
Rebased on master.

**Comment by bear454** [comment]
Results of dcbb4d7:

Screen Shot 2020-10-22 at 17 31 26

**Comment by bear454** [comment]
Peek 2020-10-22 17-59

**Review by arbulu89 — APPROVED** [review]
Hi @bear454 ,
If the width of the screen comes with the EOS branding, I guess we can live with it.
Besides that, except the planning `in progress` gif image is not displayed yet, everything else looks fine.

**Comment by arbulu89** [comment]
Hi @bear454 ,
If the width of the screen comes with the EOS branding, I guess we can live with it.
Besides that, except the planning `in progress` gif image is not displayed yet, everything

**Review by jesusbv — APPROVED** [review]
Looks great, nice effort

**Comment by bear454** [comment]
> Hi @bear454 ,
> If the width of the screen comes with the EOS branding, I guess we can live with it.
> Besides that, except the planning `in progress` gif image is not displayed yet, everything

Since I'm going to be working in the plan page within the week, I think I'll just note that for now. Thanks for your help!

**Comment by cyntss** [comment]
Hey @bear454 , is it okay if I take some screenshots from this PR to showcase Blue Horizon as a success story in EOS?

Btw, I want to say that you have done an amazing job implementing the brand. It looks outstanding.

**Pull request merged**
