### PR TITLE
Update the plan if variables have changed since last terraform action

### PR DESCRIPTION
**Pull request by bear454**
UI/UX request to remove the 'update plan' button.

The plan will now be regenerated if any variable has changed since terraform was last run (any action).

### CODE REVIEW

**Comment by bear454** [comment]
re: #187

**Comment by bear454** [comment]
Screenshot_2020-12-08 blue-horizon demo(1)

**Review by arbulu89 — CHANGES_REQUESTED** [review]
Excellent @bear454 !
Really appreciated.
I understand the PR removes the icons from the `backward/forward` buttons too, right?

I think you forgot to remove the `fast_forward` from deploy page

**Review by arbulu89 — APPROVED** [review]
Anyway, I'm approving the PR eventually, as the fix is pretty quick, and you can commit and merge later without waiting for a new review.

**Pull request merged**
