### PR TITLE
Rollback when deployment fails

### LINKED ISSUE #103: Failed deployments should have rollback option
In the event that the `terraform apply` step fails to complete successfully, an option should be presented to the user to perform a `terraform destroy` action, and show the results.

### PR DESCRIPTION
**Pull request by jesusbv**
This Fixes #103

### CODE REVIEW

**Comment by bear454** [comment]
Screenshot(s) please.

**Comment by jesusbv** [comment]
Screenshot from 2020-07-13 16-20-42

Not available by default

**Comment by jesusbv** [comment]
Screenshot from 2020-07-13 16-21-05

**Comment by jesusbv** [comment]
Screenshot from 2020-07-13 16-21-29

**Pull request merged**
